[package]
name = "engine"
version = "0.1.0"
authors = ["anirudhb <anirudhb@users.noreply.github.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
argh = "0.1.4"
comrak = { version = "0.9.1", default-features = false }
serde = { version = "1.0.123", features = ["derive"] }
thiserror = "1.0.24"
toml = "0.5.8"
url = "2.2.1"
