name: Build

on:
  push:
    branches: [v2]

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build site
        run: cd engine && cargo run -- -f ../src/index.md
      - name: Deploy to gh pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public